### ISSUE TITLE
Help, Error Pada Saat Memulai Bot

### ISSUE THREAD

**Issue by yourtypicalbae** [replacesh/SnipeeV1-FS#1]
DevTools listening on ws://127.0.0.1:64034/devtools/browser/1420f5f9-14d5-490d-aed3-9deb21ca6e7f
Traceback (most recent call last):
  File "Snipee.py", line 129, in <module>
    browser = webdriver.Chrome(executable_path='chromedriver.exe', options=option)
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 76, in __init__
    RemoteWebDriver.__init__(
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 86
Current browser version is 90.0.4430.93 with binary path C:\Program Files\Google\Chrome\Application\chrome.exe

Sudah Coba Downgrade Ke Python 3.7 Namun Hasilnya Tetap Sama

**Comment by replacesh** [comment]
Itu karena ChromeDriver tidak sesuai sama versi Chrome.
Coba diganti chromedriver.exe di aplikai dengan yang baru sesuai versi
Google Chrome di Komputer. Download ChromeDriver [disini](https://chromedriver.chromium.org/downloads).

**Comment by yourtypicalbae** [comment]
Oke Thankyou Gan
